server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: wikidev
    url: jdbc:mysql://localhost:3306/wikidev?useUnicode=true&characterEncoding=utf8&useSSL=false
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.example.wiki.mapper: trace