server:
  port: 8880
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: wikidev
    url: jdbc:mysql://localhost:3306/wikidev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
  redis:
    port: 6379
    password: 123456789
    host: 127.0.0.1
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    password: guest
    username: guest
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.example.wiki.mapper: trace
