GET http://localhost:8081/ebook/list?name=教程
Accept: application/json

###
GET http://localhost:8081/list
Accept: application/json

###
GET http://localhost:8080/hello
Accept: application/json

###

###
POST http://localhost:8080/hello/post
Content-Type: application/x-www-form-urlencoded

name=Tom

###


{}

###

###
